### ISSUE TITLE
[privategpt] HuggingFace Token

### ISSUE THREAD

**Issue by mdima** [3x3cut0r/docker#9]
Hello, 
  I am trying to start the container, but I receive the error: 

```
Downloading tokenizer mistralai/Mistral-7B-Instruct-v0.2
Traceback (most recent call last):
  File "/home/worker/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/home/worker/app/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json
```

So I read here https://github.com/zylon-ai/private-gpt/issues/1861 that a Token is required to download that file. 

I added, as suggested above, the env variable: 
--env=HUGGINGFACE_TOKEN=xxxxxxxxxxxxx
and I accepted the agreement for the model "Mistral-7B-Instruct-v0.2" in HuggingFace, but I receive the same error. 

Can you please help? 

Thanks,
Michele

**Comment by 3x3cut0r** [comment]
hey,
the problem is, that mistralai now wants you to agree to the terms. this is also an upstream issue.
anyways ... i did not implement the env `HUGGINGFACE_TOKEN` either.
now i added it and did uploaded a new image.
try now provide your own token and it should work.

but I still have to see how this is solved at the upstream private-gpt repo as well
